version: "3"

vars:
  BUILD: build

tasks:
  cmake:
    desc: cmake
    cmds:
      - >
        echo -e "cmake args:\n$(cat cmake/args)"
      - >
        cmake -GNinja "-B{{.BUILD}}"
        $(cat cmake/args)
        .
  clean:
    desc: clean cmake build
    cmds:
      - rm -rf {{.BUILD}}
  build:
    desc: build with cmake --build
    cmds:
      - cmake --build "{{.BUILD}}" --parallel $(nproc)
  all:
    desc: cmake and build all targets
    deps:
      - cmake
    cmds:
      - task build
  fmt:
    desc: format all source files
    cmds:
      - >
        find . -iname '*.h' -o -iname '*.cc' -o -iname '*.hpp' |
        clang-format --style=file -i --files=/dev/stdin
