version: "3"

vars:
  BUILD: build

tasks:
  cmake:
    desc: cmake
    cmds:
      - cmake --preset debug
      - cmake --preset release
  clean:
    desc: clean cmake build
    cmds:
      - rm -rf {{.BUILD}}
  build:
    desc: build with cmake debug preset
    deps:
      - build-debug
      - build-release
  build-debug:
    desc: build with cmake debug preset
    cmds:
      - cmake --build --preset build-debug
  build-release:
    desc: build with cmake release preset
    cmds:
      - cmake --build --preset build-release
  all:
    desc: cmake and build all targets
    deps:
      - cmake
    cmds:
      - task build
  fmt:
    desc: format all source files
    cmds:
      - >
        find . -iname '*.h' -o -iname '*.cc' -o -iname '*.hpp' |
        clang-format --style=file -i --files=/dev/stdin
